apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:2.4.1-alpine
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "10.115.240.5"
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_USER
          value: "kong-user"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-creds
              key: password
        - name: KONG_PG_DATABASE
          value: "kong"
        - name: KONG_PG_SSL_MODE
          value: "verify-ca"
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: "/etc/secrets/ssl/postgresql-server-ca"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        volumeMounts:
        - name: kong-ssl-copy
          mountPath: /etc/secrets/ssl
        - name: kong-pg-client
          mountPath: /usr/local/bin/psql
          subPath: psql
      volumes:
      - name: kong-ssl
        secret:
          secretName: kong-postgres-ssl
          defaultMode: 0600
      - name: kong-ssl-copy
        emptyDir: {}
      - name: kong-pg-client
        configMap:
          name: psql-client
      initContainers:
      - name: init-cert
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            cp /kong-ssl/* /etc/secrets/ssl/
            chmod 640 /etc/secrets/ssl/postgresql-client-key
            chmod 644 /etc/secrets/ssl/postgresql-server-ca
            chmod 644 /etc/secrets/ssl/postgresql-client-cert
        volumeMounts:
          - name: kong-ssl
            mountPath: /kong-ssl
          - name: kong-ssl-copy
            mountPath: /etc/secrets/ssl
