version: '3.8'

networks:
  kong-net:
    external: true  # Sử dụng mạng external tên là 'kong-net'

services:

  kong-db:
    image: postgres:17
    container_name: kong-db
    restart: always
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:2.4.1-alpine
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    command: kong migrations bootstrap
    restart: on-failure

  kong:
    image: kong:2.4.1-alpine
    container_name: kong
    depends_on:
      - kong-db
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: bundled,jwt
    ports:
      - "8000:8000"     # proxy
      - "8443:8443"     # proxy SSL
      - "8001:8001"     # admin API
      - "8444:8444"     # admin API SSL
    networks:
      - kong-net

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    environment:
      - "KONGA_URI=http://kong:8001"  # Địa chỉ Kong Admin API
    ports:
      - "1337:1337"  # Cổng Konga (giao diện quản lý)
    networks:
      - kong-net

volumes:
  kong-db-data:
